---
- name: Install epel release
  yum:
     name: epel-release
     state: latest

- name: Add Docker Repo
  get_url: 
       url: https://download.docker.com/linux/centos/docker-ce.repo 
       dest: /etc/yum.repos.d/docker-ce.repo
       mode: 0700
       force_basic_auth: yes

- name: Update repository
  yum: name=* 
       state=latest

- name: Install development tools
  yum:
    name: "@Development tools"
    state: present   

- name: Install Docker
  yum:
    name :
    - docker-ce
    - docker-ce-cli
    - containerd.io  
    state: latest
    update_cache: yes


- name: Install python3-pip
  yum:
    name: python3-pip
    state: latest
    
- name: Install Docker-Compose
  pip: 
    name: docker-compose
    state: latest

- name: Restart Docker
  service: 
    name: docker 
    state: restarted

- name: Make sure that Docker is active
  service:
    name: docker
    enabled: yes
